[theme]
base = "light"
primaryColor = "#1b365d"
backgroundColor = "#f4f7fb"          # Este es el fondo azulado muy sutil que elegimos
secondaryBackgroundColor = "#ffffff" # Color para tarjetas, entradas y barra lateral
textColor = "#212529"
